pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven' // Certifique-se de que a ferramenta "Maven" está configurada no Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Realiza o checkout do código do Git
                script {
                    checkout([$class: 'GitSCM', 
                              branches: [[name: 'master']], 
                              userRemoteConfigs: [[url: 'https://github.com/repoe2e/cucumber_selenium.git']]])
                }
            }
        }

        stage('Build and Test') {
            steps {
                // Execute os comandos de build e teste dentro do diretório 'cucumber_selenium/projeto.revisao.cucumber'
                dir('cucumber_selenium/projeto.revisao.cucumber') {
                    sh "${tool name: 'Maven'}/bin/mvn clean test" // Altere o comando Maven conforme necessário
                }
            }
        }

        // Adicione mais estágios conforme necessário

        stage('Publish Results') {
            steps {
                // Exemplo: Publica resultados dos testes (você pode personalizar isso)
                junit '**/target/test-classes/*.xml'
                archiveArtifacts '**/target/*.jar'
            }
        }
    }

    post {
        success {
            emailext (
                to: 'professores@e2etreinamentos.com.br',
                subject: "Build de Sucesso - ${currentBuild.fullDisplayName}",
                body: 'O build foi bem-sucedido. Parabéns!'
            )
        }
        failure {
            emailext (
                to: 'professores@e2etreinamentos.com.br',
                subject: "Build Falhou - ${currentBuild.fullDisplayName}",
                body: 'O build falhou. Verifique os logs para mais informações.'
            )
        }
    }
}
